apiVersion: v1
kind: Service
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: devops
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: teste
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: teste
  type: ClusterIP